server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    config:
      # ⭐️ 아래 4줄을 local과 docker 프로필 모두에 추가합니다.
      fail-fast: true
      retry:
        max-attempts: 20
        initial-interval: 1000
        max-interval: 2000
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/product/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**

            - id: stock-service
              uri: lb://stock-service
              predicates:
                - Path=/api/v1/stock/**
---
# --- 'local' 프로필: 로컬에서 실행 시 ---
spring.config.activate.on-profile: "local"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
# --- 'docker' 프로필: EC2에서 배포 시 ---
spring.config.activate.on-profile: "docker"
eureka:
  client:
    service-url:
      # ⭐️ Docker 네트워크의 서비스 이름으로 Eureka를 찾도록 수정
      defaultZone: http://eureka-server:8761/eureka/