server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux: # routes는 이 webflux 아래에 있어야 합니다.
          routes:
            # User Service 라우팅 규칙
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**

            # Product Service 라우팅 규칙
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/product/**

            # Order Service 라우팅 규칙
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**

            - id: stock-service
              uri: lb://STOCK-SERVICE
              predicates:
                - Path=/api/v1/stock/**

# 게이트웨이도 Eureka에 자신을 등록하도록 설정
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/