server:
  port: 8000 # 게이트웨이는 보통 8000번대 포트를 사용합니다.

spring:
  cloud:
    gateway:
      routes:
        # User-Service 라우팅 설정
        - id: user-service
          uri: http://localhost:8080 # User-Service의 실제 주소
          predicates:
            - Path=/api/v1/users/** # 이 경로로 들어오는 요청은

        # Product-Service 라우팅 설정
        - id: product-service
          uri: http://localhost:8081 # Product-Service의 실제 주소
          predicates:
            - Path=/api/v1/product/**

        # Order-Service 라우팅 설정
        - id: order-service
          uri: http://localhost:8082 # Order-Service의 실제 주소
          predicates:
            - Path=/api/v1/orders/**