spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webflux:
          routes:
            # User Service 라우팅 규칙
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**

            # Product Service 라우팅 규칙
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/product/**

            # Order Service 라우팅 규칙
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**

            - id: stock-service
              uri: lb://stock-service
              predicates:
                - Path=/api/v1/stock/**

# 게이트웨이도 Eureka에 자신을 등록하도록 설정
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG