spring:
  application:
    name: ORDER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true
    username: root
    password: 1111
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: "docker"
  datasource:
    url: jdbc:mysql://db:3306/order_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    producer:
      bootstrap-servers: kafka:29092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/