spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: 1111
  application:
    name: ORDER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/