# order-service.yml

# --- 공통 설정 ---
spring:
  application:
    name: ORDER-SERVICE

server:
  port: 8082

---
# --- 'local' 프로필 ---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: 1111
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
# --- 'docker' 프로필 ---
spring:
  config:
    activate:
      on-profile: "docker"
  datasource:
    url: jdbc:mysql://db:3306/order_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/