# product-service.yml

# --- 공통 설정 ---
spring:
  application:
    name: product-service
  cloud:
    config:
      # ⭐️ 아래 4줄을 local과 docker 프로필 모두에 추가합니다.
      fail-fast: true
      retry:
        max-attempts: 20
        initial-interval: 1000
        max-interval: 2000
  # ⭐️ Kafka 프로듀서 설정을 공통으로 뺍니다.
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

---
# --- 'local' 프로필 ---
spring:
  config:
    activate:
      on-profile: "local"
  data:
    mongodb:
      uri: mongodb://localhost:27017/product_db
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
# --- 'docker' 프로필 ---
spring:
  config:
    activate:
      on-profile: "docker"
  data:
    mongodb:
      uri: mongodb://mongodb:27017/product_db
  kafka:
    producer:
      bootstrap-servers: kafka:9092 # Docker 환경에서는 kafka 호스트 이름 사용
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/