spring:
  application:
    name: stock-service

server:
  port: 8084

---
spring:
  config:
    activate:
      on-profile: "local"
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: stock-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  redis:
    host: localhost
    port: 6379
    database: 4
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  producer:
    bootstrap-servers: localhost:9092

---
spring:
  config:
    activate:
      on-profile: "docker"
  kafka:
    consumer:
      bootstrap-servers: kafka:29092
      group-id: stock-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  redis:
    host: redis
    port: 6379
    database: 4

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

kafka:
  producer:
    bootstrap-servers: kafka:29092